
export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const FETCH_WISHLIST = 'FETCH_WISHLIST';
export const ADD_WISHLIST = 'ADD_WISHLIST';
export const REMOVE_WISHLIST = 'REMOVE_WISHLIST';
export const FETCH_COMPARE = 'FETCH_COMPARE';
export const ADD_COMPARE = 'ADD_COMPARE';
export const REMOVE_COMPARE = 'REMOVE_COMPARE';