
export const FETCH_WISHLIST = 'FETCH_WISHLIST';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_WISHLIST = 'REMOVE_WISHLIST';
export const FETCH_COMPARE = 'FETCH_COMPARE';
export const ADD_TO_COMPARE = 'ADD_TO_COMPARE';
export const REMOVE_COMPARE = 'REMOVE_COMPARE';
export const FETCH_CART = 'FETCH_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_CART = 'REMOVE_CART';
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";